### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Phoenix-100** [slint-ui/slint#1957]
Hello, I am compiling on windows10 system, and this happens, but I am running normally on windows11，Does the product not support versions below windows11?

![image](https://user-images.githubusercontent.com/39872066/206197898-539d73cd-beac-41b7-b96a-f2db5a4b643f.png)

**Comment by tronical** [comment]
Windows 10 should not be a problem. This is more likely related to the way we're trying to initialise the OpenGL context. Which version of Slint are you using? We merged a change yesterday that might fix this. Could you try the version from git and see if that works for you?

Alternatively, you can also build slint with `default-features = false`, enable the `compat-0-3-0` feature as well as `renderer-winit-skia` and then the graphics will be rendered using Direct3D instead of OpenGL. See also https://slint-ui.com/releases/0.3.2/docs/rust/slint/#backends .

**Comment by ogoffart** [comment]
Did you get any chance to figure out what went wrong?  does it still happen with Slint 0.3.3? (that has an updated version of winit and glutin)

**Comment by Phoenix-100** [comment]
> 你有机会弄清楚哪里出了问题吗？Slint 0.3.3 还会发生这种情况吗？（具有更新版本的 winit 和 glutin）

Sorry, I just saw your reply now. I tried many methods before, but the problem still hasn't been solved.
