### ISSUE TITLE
lsp crashed when edit .slint file

### ISSUE THREAD

**Issue by osenberg-x** [slint-ui/slint#3160]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', tools/lsp/completion.rs:589:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:10:35 AM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 10:10:35 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request workspace/executeCommand failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request workspace/executeCommand failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', tools/lsp/completion.rs:580:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:10:35 AM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 10:10:35 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:10:35 AM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', tools/lsp/completion.rs:580:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:10:44 AM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 10:10:44 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', tools/lsp/completion.rs:589:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 10:11:15 AM] Connection to server got closed. Server will restart.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 10:11:15 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:11:15 AM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', tools/lsp/completion.rs:580:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 10:11:16 AM] Connection to server got closed. Server will not be restarted.
The Slint Language Server crashed. This is a bug.
Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 10:11:16 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:11:16 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:11:16 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:11:16 AM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
[Error - 10:11:16 AM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/slint.slint-1.1.1/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
```
step:
1. open live-preview
2. modify componment properties in .slint file

**Comment by MoutainPL** [comment]
I also encountered this problem, but I don't know how to solve it.

**Comment by ogoffart** [comment]
Thanks for the bug report!

The interesting bits are the panic messages:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', tools/lsp/completion.rs:580:63
```
and
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', tools/lsp/completion.rs:589:55
```

I have a suspicion that this was caused by the same problem as what was reported in #2719

I just committed a change to add more debug when this panic happen.

You can try  the nightly extension tomorrow and it might fix the problem, or give a more interesting error message.

Do you maybe have strange filenames by any change?

@MoutainPL 
> I also encountered this problem,

Is this the same panic messages with the same line numbers?

**Comment by osenberg-x** [comment]
thank you very much, my slint file name is debug.slint. i'll modify name and try again

**Comment by osenberg-x** [comment]
I changed my name but still have the same problem.

And i have used nightly extension, it worked. thanks, this problem is fixed.

**Comment by MoutainPL** [comment]
@ogoffart i have used nightly extension,and this problem has indeed been solved.Thanks!
