### ISSUE TITLE
Windows with a transparent background

### ISSUE THREAD

**Issue by LoganDark** [slint-ui/slint#722]
Currently, `background: transparent` on a Window results in a black background, even with `no-frame: true`. Another use case that unfortunately cannot be served with this library: transparent splash screens. :(

**Comment by ogoffart** [comment]
I think we can fix that with the Qt backend by passing the right flag.  I don't know about the GL backend

**Comment by gizzdev** [comment]
I am trying to get the example at [https://github.com/slint-ui/slint/tree/master/api/cpp/tests/manual/platform_native](https://github.com/slint-ui/slint/tree/master/api/cpp/tests/manual/platform_native) working using SkiaRenderer but I can't find how to add alpha to the child window which is an overlay.

Basically I want a transparent main window fitting the whole screen and add opaque widgets to it.
I got everything working except the alpha part.

Any idea how to achieve this result ?

[Screenshot](https://prnt.sc/CT7lPf6YnaTw)

**Comment by ogoffart** [comment]
This bug should actually fixed in master with #2649 #2648 and #2680

> I am trying to get the example at https://github.com/slint-ui/slint/tree/master/api/cpp/tests/manual/platform_native working using SkiaRenderer but I can't find how to add alpha to the child window which is an overlay.

You may need to use some specific flag on the native window handle. 
Maybe something like this:   
https://github.com/rust-windowing/winit/blob/4ac2006cbc5a09a736bef2d23577430aadf88098/src/platform_impl/windows/window.rs#L1004
But I don't know for sure.

**Comment by Enyium** [comment]
WPF (Windows Presentation Foundation) is able to present a borderless window with an alpha mask according to the objects on it in a simple way. I did that years ago.

Using the Win32 API, the magic term is ["layered window"](https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features#layered-windows):

> if per-pixel alpha is needed, call UpdateLayeredWindow.

Using `SetLayeredWindowAttributes()` with a transparency color means you won't get anti-aliasing towards the background (the other foreign windows below).

(I tested using Slint with the Skia renderer, `no-frame: true; background: transparent;` in the component inheriting `Window`, and adding the Win32 extended window style `WS_EX_LAYERED` via `SetWindowLongPtrW()`, but the background was just black and opaque.)

**Comment by Enyium** [comment]
@ogoffart or @tronical: This bug is still there. Could this be reopened?

The `PopupWindow` element is bound to the `Window`'s client area like DOM elements to their web view. The browsers Firefox and Brave (Chromium) have tooltips, context menus and fly-outs with rounded rectangles and/or drop shadows that are always-on-top top-level windows, which aren't bound to anything smaller than the screen.

As I saw, Slint already supports this on macOS (don't know about Linux). With more support for this, Slint could provide proper context menus and tooltips by, e.g., inheriting a `ContextMenu` type from `Window`. Because of the theming Slint does, self-rendered tooltips, which could also inherit `Window`, may be the way to go instead of going the route of native tooltips. If you'd try to imitate them, though: Native Windows tooltips - just like menus - have drop shadows and fade in and out.

It seems you have to pipe all rendering through `UpdateLayeredWindow()`/`UpdateLayeredWindowIndirect()` by drawing into a memory DC and then calling one of these functions to make this work.

**Comment by tronical** [comment]
@Enyium this issue tracked the bug that transparent windows could not be created. Do I understand correctly that you're suggesting that this regresses? If yes, on which platform? Could you also elaborate how this bug relates to popup windows?

**Comment by Enyium** [comment]
> this issue tracked the bug that transparent windows could not be created. Do I understand correctly that you're suggesting that this regresses? If yes, on which platform? 

This is about Windows. I have no idea whether it worked at any point in the past on Windows, but it didn't with Slint v1.7.1.

> Could you also elaborate how this bug relates to popup windows?

First of all: Pop-up windows like context menus, tooltips and fly-outs should be always-on-top top-level windows. The classic case is a context menu or a tooltip that partially overlaps the window that brought it into existence, not being bound by its client area. Just look at these elements in browsers (also give the window a really small height and show a fly-out by clicking on a toolbar icon).

Context menu in Firefox:

![context_menu_firefox](https://github.com/user-attachments/assets/398df95f-c73f-49c2-aafc-c589e5c81374)

Fly-out in Brave (Chromium):

![flyout_brave](https://github.com/user-attachments/assets/70caaaae-07cf-43c7-b9c6-49207bc434f6)

Tooltip in Firefox (text had HTML `title` attribute):

![tooltip_firefox](https://github.com/user-attachments/assets/22c99a7b-112e-4d16-9ab5-28043e793ad2)

As you can see, all of these examples have transparent pixels, based on an alpha mask (rounded corners and drop shadows), while not being bound to the client area of a window. They are separate top-level windows with always-on-top flag set. Slint's current `PopupWindow` can't compete with that, because it's bound to the window's client area.

**Comment by ogoffart** [comment]
@Enyium Thanks, but please re-open separate issue, as this old issue has too much history about a different.
`background:transparent` is supposed to work (and it works for me on Linux) and if it doesn't, please open a bug with details and screenshot.)

As for PopupWindow, this is a different issue. They don't have a background anyway so it should always be transparetnb y default. And they are limited to the parent window because of https://github.com/slint-ui/slint/issues/2375

**Comment by Enyium** [comment]
Continued in #6020.
