### ISSUE TITLE
Slint Language Server Crashed

### ISSUE THREAD

**Issue by cap4096** [slint-ui/slint#8089]
### Bug Description

I do not use slint at all, but when running a yocto linux build in a VSCode terminal I get this:

rror running LSP server: Failed to convert path
[Error - 8:58:57 PM] Server process exited with code 0.
[Info  - 8:58:57 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
Error running LSP server: Failed to convert path
[Error - 8:59:08 PM] Server process exited with code 0.
[Info  - 8:59:08 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
Error running LSP server: Failed to convert path
[Info  - 8:59:09 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues
[Error - 8:59:09 PM] Server process exited with code 0.
Error running LSP server: Failed to convert path
[Error - 8:59:12 PM] Server process exited with code 0.
[Info  - 8:59:12 PM] Connection to server got closed. Server will restart.
true
The Slint Language Server crashed. This is a bug. Please open an issue on https://github.com/slint-ui/slint/issues

The yocto build is running  in a container that is based on Debian (if that is important).
VSCode has loaded these plugins:

				"ms-python.python",
				"streetsidesoftware.code-spell-checker",
				"ms-vscode.makefile-tools",
				"ms-vscode.cmake-tools",
				"ms-vscode.cpptools",
				"ms-vscode.cpptools-themes",
				"mads-hartmann.bash-ide-vscode",
				"maarti.jenkins-doc",
				"marus25.cortex-debug",
				"ms-azuretools.vscode-docker"

### Reproducible Code (if applicable)

```slint

```

### Environment Details

- Slint Version:
- Platform/OS:
- Programming Language:
- Backend/Renderer:

**Comment by hunger** [comment]
Interesting! Are there .slint files in your project somewhere? Or rust files?

**Comment by tronical** [comment]
Possible duplicates: #7333 and #4926

**Comment by tronical** [comment]
All of these have in common that WSL is involved. And somehow the path conversion is a fatal error for the LSP?

**Comment by hunger** [comment]
The LSP converts back and forth URLs to Paths all over the place and that is an operation that can fail:-(

**Comment by ogoffart** [comment]
We should "fix" how path/url conversion happens so that we don't run into errors.

At the minimum, something should be done so that the error message is actionable/understandable by users.

**Comment by tronical** [comment]
> The LSP converts back and forth URLs to Paths all over the place and that is an operation that can fail:-(

Is there a reason that this failure is fatal to the process, or is that a bug?

**Comment by cap4096** [comment]
Rust files exists in:

* gcc-13.3.0
* qemu 8.2.3
* binutils / gdb
* meson
* linux / linux-headers

There are no .slint / *.slint files.

**Comment by tronical** [comment]
I’ve merged a change to improve diagnostics and perhaps even avoid the panic. It will be in tomorrow’s nightly build.

**Comment by ogoffart** [comment]
@tronical So this is fixed now ?

**Comment by kristof-mattei** [comment]
I still have the issue. Since https://github.com/slint-ui/slint/pull/8155 is merged in I now see something like 

```
Failed to convert path for dropping document: vscode-remote://wsl%2Bubuntu/path-to-source/src/ui/todo.slint
```

Happy to test any custom builds.

**Comment by kristof-mattei** [comment]
Issue seems to be here:

https://github.com/slint-ui/slint/blob/af0b3822c64a5597e628c7ad487f1273f57356cf/tools/lsp/common.rs#L120-L128

The protocol is not `builtin`, but this url cannot be treated as a path:

https://github.com/slint-ui/slint/blob/af0b3822c64a5597e628c7ad487f1273f57356cf/tools/lsp/common.rs#L124
