### ISSUE TITLE
Android specific button mapping

### ISSUE THREAD

**Issue by guimath** [slint-ui/slint#8323]
### Feature Description

I think there are a lot of Android specific buttons that should have a way to be handled and don't.

### Example: Keycode::Back 
Currently, back button presses cannot be handled by the app, as they are not mapped to anything in `androidwindowadapter.rs` and are thus marked as unhandled and will result in quiting the app. 

This is not ideal because there is then no way to add logic around it: 
- In a `FocusScope` like how you would handle other key presses doesn't work because it is not called 
- from the backend using the `init_with_event_listener` doesn't work because input is processed by slint and so cannot be detected using `input_events_iter`. 

I have tried adding my own key code map for `Keycode::Back` and it works, but the event cannot be Unhandled (which is ideally what would happen if the key-pressed was rejected in the slint FocusScope). This is acceptable in my case as I can then manually close instead of relying on reject but on other key presses might be a bit more annoying...

### Possible solutions
I think the best possible way would be to use the `EventResult` to detect if an event should be handled or unhandled.
- `-` Requires a bunch of code changes (i think, haven't look into it too much)
- `+` Cross platform and intuitive

Another solution would be to add another key handler that could be instantiated to process those from the rust code. It would only get called for those specific keys that aren't currently mapped to anything. 
- `-` Less intuitive 
- `-` Requires a lot more code on the user's end 
- `+` Faster to implement.

### Product Impact

I'm building an app and it would be usefull to go back to the previous screen.
For many apps this feels quite limiting, especially since handeling those buttons is currently impossible without changing the slint source code.

**Comment by ogoffart** [comment]
Thanks for filing an issue.

Indeed, we should map the back button to a key so it can be handled by a focus scope.
And yes, it is unfortunate that the dispatch_event doesn't return a result telling that the key was handled. We could get around this by using the private API (`process_mouse_input`) in the backend which can be changed to account for that.

**Comment by eminfedar** [comment]
Any progress on detecting back button press on android phones?

**Comment by loganmc10** [comment]
Wouldn't it be fixed by this? https://github.com/slint-ui/slint/pull/9172

**Comment by ogoffart** [comment]
Yes, it should be fixed by #9172

**Comment by Nubuki-all** [comment]
Is this fix live in ver 1.17.1?
I still can't handle back key presses in focusScope
@ogoffart

**Comment by ogoffart** [comment]
Yes, it is in 1.17.1

**Comment by Nubuki-all** [comment]
> Yes, it is in 1.17.1

Thanks for the reply 
It was an error on my end
